### ISSUE TITLE
About given testing 

### ISSUE THREAD

**Issue by chihiro0019** [devsim/devsim#10]
Dear,  juanesanchez-san.

Since I am a novice of DevSim, I can't analyze what's wrong with the given testing.
Please advice. Seems sqlite3.something is missing.

[root@JPC20320148 testing]# pwd
/install/DevSim/devsim-master/testing
[root@JPC20320148 testing]# ls sqli*
sqlite1.out  sqlite1.tcl  sqlite2.out  sqlite2.py  sqlite3.out  sqlite3.py
[root@JPC20320148 testing]# devsim_tcl sqlite1.tcl

----------------------------------------

 DEVSIM

 Version: Beta 0.01

 Copyright 2009-2014 Devsim LLC

----------------------------------------

can't find package sqlite3
    while executing
"package require sqlite3"
    (file "sqlite1.tcl" line 15)

**Comment by juanesanchez** [comment]
Hi,

Please install:
yum install sqlite-tcl

**Comment by chihiro0019** [comment]
Thanks, it was solved.
