### ISSUE TITLE
Suppressing Messages from DevSim

### ISSUE THREAD

**Issue by chihiro0019** [devsim/devsim#12]
Can I suppress messages from DevSim ? as long as it is running normally.
And can I get CPU time information ?
I couldn't know how to do it from devsim_py -h.

And how can I run DevSim with multi cores ?

Sorry for my many questions.

**Comment by juanesanchez** [comment]
Hi,

You can use shell redirection stdout and stderr.

To redirect stdout in bash:
devsim_py test.py > /dev/null

To redirect stderr and stdout:
devsim_py test.py >& /dev/null

See the following for examples:
http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-3.html

**Comment by juanesanchez** [comment]
To get CPU time information:
time devsim_py test.py

**Comment by chihiro0019** [comment]
Thank you very much, 
/usr/bin/time was more friendly to me.
I am using csh.
