### ISSUE TITLE
issue with EngineAPI.hh and ModelExprData.cc on OS X 10.10

### ISSUE THREAD

**Issue by d679** [devsim/devsim#14]
Hi, 
I am having a problem building devsim. I am getting the following errrors, and was wondering if you have some suggestions?

[  6%] Built target Geometry
[ 17%] Built target models
[ 27%] Built target modelcomp
[ 29%] Built target math
[ 31%] Built target Equation
[ 31%] Building CXX object src/AutoEquation/CMakeFiles/AutoEquation.dir/ModelExprEval.o
[ 31%] Building CXX object src/AutoEquation/CMakeFiles/AutoEquation.dir/ModelExprData.o
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:4:1: error: 
      expected unqualified-id
<!DOCTYPE html>
^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:13:46: error: 
      non-ASCII characters are not allowed outside of literals and identifiers
    <title>devsim/ModelExprData.cc at master · devsim/devsim · GitHub</title>
                                             ^~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:13:63: error: 
      non-ASCII characters are not allowed outside of literals and identifiers
    <title>devsim/ModelExprData.cc at master · devsim/devsim · GitHub</title>
                                                             ^~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:50:30: warning: 
      missing terminating ' character [-Winvalid-pp-token]
    <meta content="authenticity_token" n...
                             ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:95:32: warning: 
      missing terminating ' character [-Winvalid-pp-token]
      <form accept-charset="UTF-8" actio...
                               ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:754: error: 
      C++ requires a type specifier for all declarations
  ...protocol_type=clone" class="inline-form js-clone-selector-form " data-fo...
     ^~~~~~~~~~~~~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:768: error: 
      use of undeclared identifier 'clone'
  ...clone" class="inline-form js-clone-selector-form " data-form-nonce="90d1...
     ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:932: error: 
      unknown type name 'padding'
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                           ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:939: error: 
      expected unqualified-id
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                                  ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:942: error: 
      unknown type name 'display'
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                                     ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:949: error: 
      expected unqualified-id
  ...method="post"><div style="margin:0;padding:0;display:inline"><input name...
                                                         ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:1006: error: 
      expected unqualified-id
  ...name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_t...
                                              ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:284:1244: warning: 
      missing terminating '"' character [-Winvalid-pp-token]
  ...js-clone-selector" data-protocol="subversion" type="submit">Subversion</...
                                                               ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:408:3: error: 
      expected unqualified-id
  </div>
  ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:530:151: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&quot;</span>ModelExprData.hh<sp...
                                                   ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:530:201: error: 
      expected unqualified-id
  ...class="pl-pds">&quot;</span></span></td>
                          ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:534:151: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&quot;</span>NodeScalarData.hh<s...
                                                   ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:534:202: error: 
      expected unqualified-id
  ...class="pl-pds">&quot;</span></span></td>
                          ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:538:151: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&quot;</span>EdgeScalarData.hh<s...
                                                   ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:538:202: error: 
      expected unqualified-id
  ...class="pl-pds">&quot;</span></span></td>
                          ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:542:151: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&quot;</span>TriangleEdgeScalarD...
                                                   ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprData.cc:542:210: error: 
      expected unqualified-id
  ...class="pl-pds">&quot;</span></span></td>
                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make[2]: *** [src/AutoEquation/CMakeFiles/AutoEquation.dir/ModelExprData.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 42%] Built target GeomModels
[ 56%] Built target meshing
[ 58%] Built target Data
[ 61%] Built target circuitData
[ 64%] Built target circuitIdeal
[ 66%] Built target circuitSources
Scanning dependencies of target MathEval
[ 67%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/Bernoulli.o
[ 67%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/Fermi.o
[ 68%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/MathEval.o
In file included from /Users/sonia/Documents/Simulations/devsim/src/AutoEquation/ModelExprEval.cc:43:
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:4:1: error: 
      expected unqualified-id
<!DOCTYPE html>
^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:13:43: error: 
      non-ASCII characters are not allowed outside of literals and identifiers
    <title>symdiff/EngineAPI.hh at master · devsim/symdiff · GitHub</title>
                                          ^~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:13:61: error: 
      non-ASCII characters are not allowed outside of literals and identifiers
    <title>symdiff/EngineAPI.hh at master · devsim/symdiff · GitHub</title>
                                                           ^~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:50:30: warning: 
      missing terminating ' character [-Winvalid-pp-token]
    <meta content="authenticity_token" n...
                             ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:95:32: warning: 
      missing terminating ' character [-Winvalid-pp-token]
      <form accept-charset="UTF-8" actio...
                               ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:754: error: 
      C++ requires a type specifier for all declarations
  ...protocol_type=clone" class="inline-form js-clone-selector-form " data-fo...
     ^~~~~~~~~~~~~
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:768: error: 
      use of undeclared identifier 'clone'
  ...clone" class="inline-form js-clone-selector-form " data-form-nonce="90d1...
     ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:932: error: 
      unknown type name 'padding'
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                           ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:939: error: 
      expected unqualified-id
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                                  ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:942: error: 
      unknown type name 'display'
  ...data-remote="true" method="post"><div style="margin:0;padding:0;display:...
                                                                     ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:949: error: 
      expected unqualified-id
  ...method="post"><div style="margin:0;padding:0;display:inline"><input name...
                                                         ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:1006: error: 
      expected unqualified-id
  ...name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_t...
                                              ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:284:1244: warning: 
      missing terminating '"' character [-Winvalid-pp-token]
  ...js-clone-selector" data-protocol="subversion" type="submit">Subversion</...
                                                               ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:403:126: warning: 
      missing terminating '"' character [-Winvalid-pp-token]
  ...class="message" data-pjax="true" title="Support for Mac OS X Mavericks 1...
                                            ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:404:24: warning: 
      missing terminating '"' character [-Winvalid-pp-token]
Update source for c++0x">Support for Mac OS X Mavericks 10.9.</a>
                       ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:539:149: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&lt;</span>memory<span class="pl...
                                                 ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:539:187: error: 
      expected unqualified-id
  ...class="pl-pds">&lt;</span>memory<span class="pl-pds">&gt;</span></span><...
                                                              ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:543:151: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&quot;</span>import.hh<span clas...
                                                   ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:543:194: error: 
      expected unqualified-id
  ...class="pl-pds">&quot;</span>import.hh<span class="pl-pds">&quot;</span><...
                                                                     ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:547:149: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&lt;</span>string<span class="pl...
                                                 ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:547:187: error: 
      expected unqualified-id
  ...class="pl-pds">&lt;</span>string<span class="pl-pds">&gt;</span></span><...
                                                              ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:551:149: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&lt;</span>vector<span class="pl...
                                                 ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:551:187: error: 
      expected unqualified-id
  ...class="pl-pds">&lt;</span>vector<span class="pl-pds">&gt;</span></span><...
                                                              ^
/Users/sonia/Documents/Simulations/devsim/src/AutoEquation/EngineAPI.hh:555:149: error: 
      expected unqualified-id
  ...<span class="pl-s"><span class="pl-pds">&lt;</span>set<span class="pl-pd...
                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
5 warnings and 20 errors generated.
make[2]: *** [src/AutoEquation/CMakeFiles/AutoEquation.dir/ModelExprEval.o] Error 1
make[1]: *** [src/AutoEquation/CMakeFiles/AutoEquation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/MiscMathFunc.o
[ 69%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/MathWrapper.o
[ 69%] Building CXX object src/MathEval/CMakeFiles/MathEval.dir/MathPacket.o
[ 69%] Linking CXX static library libMathEval.a
[ 69%] Built target MathEval
make: *** [all] Error 2

**Comment by juanesanchez** [comment]
Hi,

The error messages look like the files are html instead of C++ source 
code.  Please make sure that the files are downloaded correctly, and 
they somehow did not become converted to a different format.

If you try:
make VERBOSE=1

this will tell the command line being invoked by the compiler and may 
help to debug issues.

**Comment by d679** [comment]
Thank you, it works now.

Sonia

On Aug 26, 2015, at 10:14 PM, juanesanchez <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

The error messages look like the files are html instead of C++ source
code. Please make sure that the files are downloaded correctly, and
they somehow did not become converted to a different format.

If you try:
make VERBOSE=1

this will tell the command line being invoked by the compiler and may
help to debug issues.
