### ISSUE TITLE
Is it possible to install the program with "pip install" command?

### ISSUE THREAD

**Issue by extremewaysback** [devsim/devsim#20]
It would be much convenient that we could install with "pip install" command

**Comment by juanesanchez** [comment]
That is something that I've been thinking about.  If you want to compile from source, you can use the build files
https://github.com/devsim/devsim/blob/master/.travis.yml  (linux, mac os x)
https://github.com/devsim/devsim/blob/master/appveyor.yml (windows)

as guides for building.  There are also binary releases available which would work with almost any Python 2.7 distribution:
https://github.com/devsim/devsim/releases/latest

**Comment by extremewaysback** [comment]
@juanesanchez Hope see the package soon~.~
