### ISSUE TITLE
segmentation fault on 3d element model evaluation

### ISSUE THREAD

**Issue by nzampa** [devsim/devsim#21]
Hi,

I was trying to simulate a 3D device using mesh adaptation in a
way similar to that in devsim_bjt_example, but devsim crashes with
a segmentation fault.
I found that this happens when evaluating an element model,
derived either from a node model or an edge model, if the equation
that defines it is more complex than simple additions or the like.
This behaviour is seen only in 3D simulations.
Since I don't know if I made something wrong, I've prepared a simple
example using the same code for both 2D and 3D simulations.
Just run devsim_py test.py dim, where dim is either 3 for 3D, or
anything else for 2D, and see if you can reproduce it. 
The same happens if, as an extreme simplification, I replace "sinc"
with the basic node model "x".

Best regards,

Nicola

[test.zip](https://github.com/devsim/devsim/files/876408/test.zip)

**Comment by tcaduser** [comment]
Thanks for your report.  The error was due to a coding error.  An object was not being copied properly, leading to a program crash.  Please let me know if you encounter any more issues.

**Comment by tcaduser** [comment]
Hello Nicola,

Please let me know if the fix worked for you.  I would be very interested in knowing how your project works out.

Regards,

Juan
