### ISSUE TITLE
can m1 MacBook Pro  arm use this project

### ISSUE THREAD

**Issue by fendou1997** [devsim/devsim#67]
can m1 MacBook Pro  arm use this project

**Comment by tcaduser** [comment]
I do not have access to this hardware, but it appears that this project will run on M1 hardware using Rosetta 2.
https://support.apple.com/en-us/HT211861
https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment

You would need to install the Intel version of Anaconda Python with the MKL package.

**Comment by fendou1997** [comment]
I have solved this problem, using anaconda, thank you
