### ISSUE TITLE
If the devsim can be used in the modelling of new materials such as SiC

### ISSUE THREAD

**Issue by fendou1997** [devsim/devsim#80]
Dear author:

I want to know if the devsim can be used for the modelling of anisotropy materials such as SiC by tcl instead of modify the basic codes of devsim.
If the basic codes of the devsim must be modified, what about the difficulty?

**Comment by tcaduser** [comment]
I apologize for the late response.  If you are still interested in the software, please open start a discussion at https://forum.devsim.org
