### ISSUE TITLE
If more information can be offered about the fluxterm in the interface_equation?

### ISSUE THREAD

**Issue by fendou1997** [devsim/devsim#83]
**Before opening an issue, please create a discussion concerning your request at** https://forum.devsim.org

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
__

**Comment by tcaduser** [comment]
This is discussed here:
https://forum.devsim.org/t/could-the-more-information-can-be-offered-about-fluxterm-in-interface-equation/66/3
