### ISSUE TITLE
The calculation of heat generation

### ISSUE THREAD

**Issue by ZhenglaiT** [devsim/devsim#93]
Hello everyone!
I am trying to calculate the heat generation and temperature distribution. Furthermore, I want to consider the  simulation calculation of thermoelectric coupling. 
Currently, I am calculating the temperature field considering only Joule heating based on the example of a 2D MOSFET. The control equation are below:
![image](https://user-images.githubusercontent.com/101865718/197916944-3b42c14a-99c7-4166-b6ec-3031b2c2ef4a.png)
To make sure that my code assembles the equations correctly, I first set up a uniform heat source for the calculations. Attached is my modified code.But I meet some problems. 

The most confused questions it that the absolute value of the temperature setting affects the convergence of the results. If I set the boundary or initial temperature as a few hundred kelvins, the error of "Convergence failed“ will appear. However,  If I set the boundary or initial temperature as a few kelvins. Like :
`    set_parameter(device=device, name="drain_biasT", value=3)
    set_parameter(device=device, name="source_biasT", value=3)
    set_parameter(device=device, name="gate_biasT", value=3)
    set_parameter(device=device, name="body_biasT", value=2)`
I can get the results of temperature:
![image](https://user-images.githubusercontent.com/101865718/197919623-942c9574-01e5-4c17-af7c-8b513c9258ae.png)

Rewrite in 2022/10/28. I deleted some problem in my learning process. But I still can't understand why the absolute value of temperature affects the convergence.

[Heat_generation calculation.zip](https://github.com/devsim/devsim/files/9888514/Heat_generation.calculation.zip)

**Comment by ZhenglaiT** [comment]
I'm sorry that my heat source setting has an effect on the temperature distribution in fact, but the value should not be too large to avoid data overflow

**Comment by ythran** [comment]
I think Github is not the best place to discuss how to use Devsim. You can migrate this question to the forum of Devsim
https://forum.devsim.org/

**Comment by ZhenglaiT** [comment]
Hi ythran&nbsp;
I am sorry for this. I create this problem in the forum originally. But Juan told me to create an issue in the github. I will be careful in the next time. Thank you for your suggestion.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devsim/devsim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devsim/devsim] The calculation of heat generation (Issue #93)





 
I think Github is not the best place to discuss how to use Devsim. You can migrate this question to the forum of Devsim
 https://forum.devsim.org/

**Comment by tcaduser** [comment]
Hi @ZhenglaiT 

Please try out this package of files.  If you want to understand my changes, please discuss them on the forum.
[Heat_generation-first.zip](https://github.com/devsim/devsim/files/9888884/Heat_generation-first.zip)

The modified module files are now located in the `tphysics` subdirectory.

**Comment by tcaduser** [comment]
Hi @ZhenglaiT 

Thanks for sharing your work:
[https://github.com/ZhenglaiT/MOSFET-simulation](https://github.com/ZhenglaiT/MOSFET-simulation)
