### ISSUE TITLE
Contact definition error message always refers to contacts needing to be 2D

### ISSUE THREAD

**Issue by simbilod** [devsim/devsim#97]
**This template is for bug reporting. For general questions about the simulator, please create a new discussion at** https://forum.devsim.org

**Describe the bug**
In a 2D simulation using a gmsh 2D mesh, defining a 2D region for contact produces an error with message `Contact <contact name> region name <region name> must be 2 dimensional to be a contact.`

**To Reproduce**
See above

**Expected behavior**
From the example at `https://github.com/devsim/devsim/blob/d970ec9c55de6739a28a040183a5e5b152f8c068/examples/mobility/` where the drain and source contacts are 1-dimensional objects according to the msh file, it seems that the error message should promp the user to create a 1D contact if the simulation is in 2D. 

A generic error message mentionning contacts needing to be "N-1"-dimension could do.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Debian

**Additional context**

**Comment by tcaduser** [comment]
Hi @simbilod 

Thanks for reporting this.  I think this may be straightforward and will be fixed in a future release.

**Comment by tcaduser** [comment]
This should be fixed with release 2.3.7
